### ISSUE TITLE
Disable VMX by default

### ISSUE THREAD

**Issue by josdotso** [InfraSIM/infrasim-compute#94] opened 2016-09-15 14:31 UTC
The way things are wired with YAML + defaults, VMX is on by default and opting out of all CPU "features" is awkward if it works at all (will test that with an empty features YAML array).  

https://github.com/InfraSIM/infrasim-compute/blob/master/infrasim/model.py#L131

I ran into an issue where VMX caused my QEMU boot to hang indefinitely so this is non-trivial to debug for folks affected.

**Comment by sharkconi** [comment] 2016-09-19 01:53
@josdotso Sounds strange.  The "VMX" feature should has no side effects. 
Can you show me your running environment? Thanks

**Comment by josdotso** [comment] 2016-09-19 13:13
I have QEMU running no-kvm.  I found I need CPU type qemu64 and feature "+mmx" to get things going.  I would not need "+mmx" but the default is "+vmx" which I believe requires KVM.  Thanks!

**Comment by fub2** [comment] 2016-09-20 03:20
Guess I see your problem, on my environment, I saw qemu was running with command line like:
'''
qemu-system-x86_64-vnc:1-namenode-0-node-devicesga--enable-kvm-smbiosfile=/root/.infrasim/node-0/data/quanta_d51_smbios.bin-bootncd-machineq35,usb=off,vmport=off-chardevsocket,id=mon,host=127.0.0.1,port=2345,server,nowait-monchardev=mon,id=monitor-serialmon:udp:127.0.0.1:9003,nowait-uuid45429841-fa59-4edb-93fc-adead4c20f55-chardevsocket,id=ipmi0,host=127.0.0.1,port=9002,reconnect=10-deviceipmi-bmc-extern,chardev=ipmi0,id=bmc0-deviceisa-ipmi-kcs,bmc=bmc0-netuser-netnic-deviceahci,id=sata0-drivefile=/root/.infrasim/sda.img,format=qcow2,if=none,id=drive0,cache=writeback-deviceide-hd,bus=sata0.0,drive=drive0-m1024-cpuHaswell,+vmx-smp2,sockets=2,cores=1,threads=1
'''
Some recommendation I'd have is:
1. for --enable-kvm, since there's no-kvm in your machine, infrasim logic should automatically disable kvm when running qemu. Nothing need to be concerned. Infrasim also supports disable kvm with "kvm_enabled: false" in ymal configuration file on a machine really supports kvm.
2. for +vmx, agree it shouldn't be hard-coded here. It is specifically for simulation a 2-socket, haswell processors based system. @sharkconi can we simply remove +vmx as default and combine option of "-cpu haswell" together with "+vmx"?
3. "+mmx" which is depending in QEMU capability to support mmx instruction set. I think it would need dig into qemu to check it out.

**Comment by fub2** [comment] 2016-09-20 05:20
@josdotso 
https://codecommunity.slack.com/messages/infrasim is channel we could use to have conversations. 
visit http://community.emccode.com/ to get invitation if you have problem joining in the channel.

**Comment by sharkconi** [comment] 2016-10-09 02:50
@josdotso Actually, we can remove the “-cpu ” and “+vmx”, which will lead to the bad performance of qemu and can’t generate VM if you using EXSi as guest OS.

**Comment by sharkconi** [comment] 2016-10-09 03:09
@josdotso As for "+mmx" instruction, it's a very old Intel i486 cpu instruction, which is already contained inside qemu.  You do not need to specify it.

**Comment by fub2** [comment] 2016-11-01 08:16
@josdotso “+vmx” won't cause any problem after we update qemu infrasim leverage to v2.6.2. Seems one issue you've seen should be caused by qemu v2.6.0. The update was made through qemu deb file which we built it and upload it to bintray. Re-running "infrasim-init" will update that qemu binary.

Can you try run this and confirm? I'm going to close this issue.

**Closed** 2016-11-10 09:33 UTC
